### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by RandyGaul** [EasyPeasyLemonSqueezy/MadCat#1]
I have a quick question if you don't mind. Just curious, what's so shitty about this code?

https://github.com/EasyPeasyLemonSqueezy/MadCat/blob/ff1b1ed0614a43a2c8caaf34b7051dc70b477b09/MadCat/NutEngine/Physics/Collider/AABBvsAABB.cs#L58

**Comment by Learko** [comment]
Sorry, nothing, I was upset that the problem wasn't as trivial as I expected. *\<shame\>*
https://github.com/EasyPeasyLemonSqueezy/MadCat/commit/b35cbbf6287332b501b8bc77c617cdd9b5e2826a

**Comment by RandyGaul** [comment]
Aww! Well if you have any questions feel free to message me :)

**Comment by Learko** [comment]
Thanks!
